#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'shaderapid3d8ff'

def options(opt):
	return

def configure(conf):
	conf.env.append_unique('DEFINES',[
		'SHADERAPID3D8FF',
		'SHADER_DLL_EXPORT',
		'PROTECTED_THINGS_ENABLE',
		'strncpy=use_Q_strncpy_instead',
		'_snprintf=use_Q_snprintf_instead',
	])
	
	# Don't use DX-to-GL abstraction - we're using native D3D9
	# This prevents rendermechanism.h from including OpenGL headers
	# NOTE: We explicitly do NOT define DX_TO_GL_ABSTRACTION

def build(bld):
	source = [
		'shaderdeviced3d8ff.cpp',
		'../shaderapidx9/hardwareconfig.cpp',
		'shaderapid3d8ff.cpp',
		'shaderapid3d8ff_impl.cpp',
		'shaderapid3d8ff_state.cpp',
		'shaderapid3d8ff_stubs.cpp',
		'mesh_d3d8ff.cpp',
		'material_d3d8ff.cpp',
		'../shaderapidx9/shaderdevicebase.cpp',
		'../shaderapidx9/shaderapibase.cpp',
	]

	includes = [
		'.',
		'../',
		'../../public',
		'../../public/tier0',
		'../../public/tier1',
		'../../public/tier2',
		'../../common'
	]

	defines = [
		'SHADERAPID3D8FF_EXPORTS',
		'SHADER_DLL_EXPORT'
	]

	libs = [
		'tier0',
		'tier1',
		'tier2',
		'vstdlib',
		'mathlib',
		'bitmap',
		'vtf'
	]

	# External/system libraries
	external_libs = []
	
	# Add D3D9 libraries for Windows
	if bld.env.DEST_OS == 'win32':
		external_libs += ['d3d9', 'd3dx9', 'user32']

	install_path = bld.env.LIBDIR

	bld.shlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		lib      = external_libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

